export const spanish_books_old_testament = [
  { value: "GEN", label: "Génesis", chapters: 50 },
  { value: "EXO", label: "Éxodo", chapters: 40 },
  { value: "LEV", label: "Levítico", chapters: 27 },
  { value: "NUM", label: "Números", chapters: 36 },
  { value: "DEU", label: "Deuteronomio", chapters: 34 },
  { value: "JOS", label: "Josué", chapters: 24 },
  { value: "JDG", label: "Jueces", chapters: 21 },
  { value: "RUT", label: "Rut", chapters: 4 },
  { value: "1SA", label: "1 Samuel", chapters: 31 },
  { value: "2SA", label: "2 Samuel", chapters: 24 },
  { value: "1KI", label: "1 Reyes", chapters: 22 },
  { value: "2KI", label: "2 Reyes", chapters: 25 },
  { value: "1CH", label: "1 Crónicas", chapters: 29 },
  { value: "2CH", label: "2 Crónicas", chapters: 36 },
  { value: "EZR", label: "Esdras", chapters: 10 },
  { value: "NEH", label: "Nehemías", chapters: 13 },
  { value: "EST", label: "Ester", chapters: 10 },
  { value: "JOB", label: "Job", chapters: 42 },
  { value: "PSA", label: "Salmos", chapters: 150 },
  { value: "PRO", label: "Proverbios", chapters: 31 },
  { value: "ECC", label: "Eclesiastés", chapters: 12 },
  { value: "SNG", label: "Cantares", chapters: 8 },
  { value: "ISA", label: "Isaías", chapters: 66 },
  { value: "JER", label: "Jeremías", chapters: 52 },
  { value: "LAM", label: "Lamentaciones", chapters: 5 },
  { value: "EZK", label: "Ezequiel", chapters: 48 },
  { value: "DAN", label: "Daniel", chapters: 12 },
  { value: "HOS", label: "Oseas", chapters: 14 },
  { value: "JOL", label: "Joel", chapters: 3 },
  { value: "AMO", label: "Amós", chapters: 9 },
  { value: "OBA", label: "Abdía", chapters: 1 },
  { value: "JON", label: "Jonás", chapters: 4 },
  { value: "MIC", label: "Miqueas", chapters: 7 },
  { value: "NAM", label: "Nahúm", chapters: 3 },
  { value: "HAB", label: "Habacuc", chapters: 3 },
  { value: "ZEP", label: "Sofonias", chapters: 3 },
  { value: "HAG", label: "Hageo", chapters: 2 },
  { value: "ZEC", label: "Zacarías", chapters: 14 },
  { value: "MAL", label: "Malaquias", chapters: 4 },
];
