export const newtestamentbooks = [
  { value: "MATTHEW", label: "Matthew", chapters: 28 },
  { value: "Mark", label: "Mark", chapters: 16 },
  { value: "Luke", label: "Luke", chapters: 24 },
  { value: "John", label: "John", chapters: 21 },
  { value: "Acts", label: "Acts", chapters: 28 },
  { value: "Romans", label: "Romans", chapters: 16 },
  { value: "1 Corinthians", label: "1 Corinthians", chapters: 16 },
  { value: "2 Corinthians", label: "2 Corinthians", chapters: 13 },
  { value: "Galatians", label: "Galatians", chapters: 6 },
  { value: "Ephesians", label: "Ephesians", chapters: 6 },
  { value: "Philippians", label: "Philippians", chapters: 4 },
  { value: "Colossians", label: "Colossians", chapters: 4 },
  { value: "1 Thessalonians", label: "1 Thessalonians", chapters: 5 },
  { value: "2 Thessalonians", label: "2 Thessalonians", chapters: 3 },
  { value: "1 Timothy", label: "1 Timothy", chapters: 6 },
  { value: "2 Timothy", label: "2 Timothy", chapters: 4 },
  { value: "Titus", label: "Titus", chapters: 3 },
  { value: "Philemon", label: "Philemon", chapters: 1 },
  { value: "Hebrews", label: "Hebrews", chapters: 13 },
  { value: "James", label: "James", chapters: 5 },
  { value: "1 Peter", label: "1 Peter", chapters: 5 },
  { value: "2 Peter", label: "2 Peter", chapters: 3 },
  { value: "1 John", label: "1 John", chapters: 5 },
  { value: "2 John", label: "2 John", chapters: 1 },
  { value: "3 John", label: "3 John", chapters: 1 },
  { value: "Jude", label: "Jude", chapters: 1 },
  { value: "Revelation", label: "Revelation", chapters: 22 },
];
