export const oldtestamentbooks = [
  { value: "GENESIS", label: "Genesis", chapters: 50 },
  { value: "EXODUS", label: "Exodus", chapters: 40 },
  { value: "LEVITICUS", label: "Leviticus", chapters: 27 },
  { value: "NUMBERS", label: "Numbers", chapters: 36 },
  { value: "Deuteronomy", label: "Deuteronomy", chapters: 34 },
  { value: "Joshua", label: "Joshua", chapters: 24 },
  { value: "Judges", label: "Judges", chapters: 21 },
  { value: "Ruth", label: "Ruth", chapters: 4 },
  { value: "1 Samuel", label: "1 Samuel", chapters: 31 },
  { value: "2 Samuel", label: "2 Samuel", chapters: 24 },
  { value: "1 Kings", label: "1 Kings", chapters: 22 },
  { value: "2 Kings", label: "2 Kings", chapters: 25 },
  { value: "1 Chronicles", label: "1 Chronicles", chapters: 29 },
  { value: "2 Chronicles", label: "2 Chronicles", chapters: 36 },
  { value: "Ezra", label: "Ezra", chapters: 10 },
  { value: "Nehemiah", label: "Nehemiah", chapters: 13 },
  { value: "Esther", label: "Esther", chapters: 10 },
  { value: "Job", label: "Job", chapters: 42 },
  { value: "Psalms", label: "Psalms", chapters: 150 },
  { value: "Proverbs", label: "Proverbs", chapters: 31 },
  { value: "Ecclesiastes", label: "Ecclesiastes", chapters: 12 },
  { value: "Song of Solomon", label: "Song of Solomon", chapters: 8 },
  { value: "Isaiah", label: "Isaiah", chapters: 66 },
  { value: "Jeremiah", label: "Jeremiah", chapters: 52 },
  { value: "Lamentations", label: "Lamentations", chapters: 5 },
  { value: "Ezekiel", label: "Ezekiel", chapters: 48 },
  { value: "Daniel", label: "Daniel", chapters: 12 },
  { value: "Hosea", label: "Hosea", chapters: 14 },
  { value: "Joel", label: "Joel", chapters: 3 },
  { value: "Amos", label: "Amos", chapters: 9 },
  { value: "Obadiah", label: "Obadiah", chapters: 1 },
  { value: "Jonah", label: "Jonah", chapters: 4 },
  { value: "Micah", label: "Micah", chapters: 7 },
  { value: "Nahum", label: "Nahum", chapters: 3 },
  { value: "Habakkuk", label: "Habakkuk", chapters: 3 },
  { value: "Zephaniah", label: "Zephaniah", chapters: 3 },
  { value: "Haggai", label: "Haggai", chapters: 2 },
  { value: "Zechariah", label: "Zechariah", chapters: 14 },
  { value: "Malachi", label: "Malachi", chapters: 4 },
];
