export const spanish_books_new_testament = [
  { value: "MAT", label: "San Mateo", chapters: 28 },
  { value: "MRK", label: "San Marcos", chapters: 16 },
  { value: "LUK", label: "San Lucas", chapters: 24 },
  { value: "JHN", label: "San Juan", chapters: 21 },
  { value: "ACT", label: "Hechos", chapters: 28 },
  { value: "ROM", label: "Romanos", chapters: 16 },
  { value: "1CO", label: "1 Corintios", chapters: 16 },
  { value: "2CO", label: "2 Corintios", chapters: 13 },
  { value: "GAL", label: "Gálatas", chapters: 6 },
  { value: "EPH", label: "Efesios", chapters: 8 },
  { value: "PHP", label: "Filipenses", chapters: 4 },
  { value: "COL", label: "Colonseses", chapters: 4 },
  { value: "1TH", label: "1 Tesalonicenses", chapters: 5 },
  { value: "2TH", label: "2 Tesalonicenses", chapters: 3 },
  { value: "1TI", label: "1 Timoteo", chapters: 6 },
  { value: "2TI", label: "2 Timoteo", chapters: 4 },
  { value: "TIT", label: "Tito", chapters: 3 },
  { value: "PHM", label: "Filemón", chapters: 1 },
  { value: "HEB", label: "Hebreos", chapters: 13 },
  { value: "JAS", label: "Santiago", chapters: 5 },
  { value: "1PE", label: "1 Pedro", chapters: 5 },
  { value: "2PE", label: "2 Pedro", chapters: 3 },
  { value: "1JN", label: "1 Juan", chapters: 5 },
  { value: "2JN", label: "2 Juan", chapters: 1 },
  { value: "3JN", label: "3 Juan", chapters: 1 },
  { value: "JUD", label: "Judas", chapters: 1 },
  { value: "REV", label: "Apocalipsis", chapters: 22 },
];
